Layout/EmptyLinesAroundModuleBody:
  Enabled: false
Layout/MultilineOperationIndentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false

#
# enable so-called "pending cops"
# after "minor" RuboCop upgrades!
#
# https://docs.rubocop.org/en/latest/versioning/#pending-cops
#

Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
