AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
  Exclude:
    - 'doc/*'
    - 'tmp/*'
    - 'pkg/*'

Layout/MultilineOperationIndentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
