#!/usr/bin/env ruby

lib = File.expand_path('../../lib', __FILE__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)
require 'git/branch/stray'

if git('rev-parse --show-toplevel').first
  Git.list_stray_branches
  exit(0)
else
  puts "Please run #{File.basename(__FILE__)} from inside a git repo!"
  exit(-1)
end

# That's all Folks!
